name: Nix Flake CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  flake-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v23
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            sandbox = relaxed

      - name: Setup Cache (Cachix)
        uses: cachix/cachix-action@v14
        with:
          name: nix-cache

      - name: Flake Check
        run: nix flake check --no-write-lock-file --show-trace

  build-systems:
    needs: flake-check
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        system:
          - laptop-asus
          - laptop-thinkpad
          - wsl
          - vps

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v23
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            sandbox = relaxed

      - name: Setup Cache (Cachix)
        uses: cachix/cachix-action@v14
        with:
          name: nix-cache

      - name: Build NixOS System
        run: |
          nix build \
            .#nixosConfigurations.${{ matrix.system }}.config.system.build.toplevel \
            --print-build-logs
